v1.2 node
Picovoice/pvrecorder pull request #70
Opened 2023-07-10 23:03 UTC by ksyeo1010

2023-07-11 23:23 UTC, laves requested changes

2023-07-11 23:23 UTC, laves commented on .github/workflows/nodejs-demos.yml
> +        node-version: [14.x, 16.x, 18.x]
you should add 20.x as well since that's current

2023-07-11 23:23 UTC, laves commented on .github/workflows/nodejs.yml
> +        node-version: [14.x, 16.x, 18.x]
20.x

2023-07-11 23:23 UTC, laves commented on README.md
> +Install NodeJS binding:
```suggestion
Install Node.js binding:
```

2023-07-11 23:23 UTC, laves commented on README.md
> +    /*const frame = recorder.readSync(), for synchronous calls*/
For this quick example, let's leave this comment out

2023-07-11 23:23 UTC, laves commented on README.md
> +To stop recording just run stop on the instance:
```suggestion
To stop recording, run stop on the instance:
```

2023-07-11 23:23 UTC, laves commented on binding/nodejs/README.md
> +const recorder = new PvRecorder(/*sets to default device*/-1, /*frame length*/ 512);
The formatting on this line is a little odd and device index can be removed since we talk about that later

2023-07-11 23:23 UTC, laves commented on binding/nodejs/README.md
> +const devices = PvRecorder.getAvailableDevices() // select index of device
'select index of device' here makes me think that `getAvailableDevices()` is going to select the index.

2023-07-11 23:23 UTC, laves commented on binding/nodejs/README.md
> +    /*const frame = recorder.readSync(), for synchronous calls*/
The mix of `/* */` and `//` comments in this block doesn't look very good

2023-07-11 23:23 UTC, laves commented on binding/nodejs/src/pv_recorder.ts
> +    deviceIndex: number = -1,
in the doc comment above, `deviceIndex` is still listed first

2023-07-11 23:23 UTC, laves commented on binding/nodejs/src/pv_recorder.ts
> +      porcupineHandleAndStatus = PvRecorder._pvRecorder.init(frameLength, deviceIndex, bufferedFramesCount);
porcupine?

2023-07-11 23:23 UTC, laves commented on binding/nodejs/test/pv_recorder.test.ts
> +    const recorder = new PvRecorder( 512, 0);
there's some weird spacing in this file - can you check the formatting?

2023-07-11 23:23 UTC, laves commented on demo/nodejs/README.md
> +
I'd remove this

2023-07-11 23:49 UTC, ksyeo1010 commented
I will fix demos once the package gets release, for some reason working-directory gets messed up on the demo builds

2023-07-12 00:16 UTC, laves approved these changes

2023-07-12 16:53 UTC, merged